services:

  # ----- Minio Submission ------
  # ------------------------------------

  minioSubmission:
    image: coollabsio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minioSubmission
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MinioRootUser}
      - MINIO_ROOT_PASSWORD=${MinioRootPass}
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
      - MINIO_SERVER_URL=http://localhost:9000
      - MINIO_IDENTITY_OPENID_CONFIG_URL=${MinioIdentityConfigURL}
      - MINIO_IDENTITY_OPENID_CLIENT_ID=${MinioIdentityID}
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET=${MinioOpenidSecret}
      - MINIO_IDENTITY_OPENID_DISPLAY_NAME=SSO_IDENTIFIER
      - MINIO_IDENTITY_OPENID_SCOPES=openid
      - MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC=off
    networks:
      - sub-net
    volumes:
      - minioSubmission_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 5 sh -c 'cat < /dev/null > /dev/tcp/127.0.0.1/9000'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s