services:
  # grant the necessary permissions to RUSTFS volumes path
  rustfs_tre_perms:
    image: alpine
    user: root
    volumes:
      - rustfs_TRE_data:/data/rustfs
    command: chown -R 10001:10001 /data/rustfs
    networks:
      - sub-net

  rustfs_TRE:
    security_opt:
      - "no-new-privileges:true"
    image: rustfs/rustfs:1.0.0-beta.7
    container_name: rustfs_TRE
    ports:
      - "9002:9002" # S3 API port
      - "9003:9003" # Console port
    environment:
      - RUSTFS_VOLUMES=/data/rustfs
      - RUSTFS_ADDRESS=0.0.0.0:9002
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9003
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_ACCESS_KEY=${TreMinioAdminUser}
      - RUSTFS_SECRET_KEY=${TreMinioAdminPassword}
      - RUSTFS_OBS_LOGGER_LEVEL=info
      - RUSTFS_REGION=us-east-1
      - RUSTFS_IDENTITY_OPENID_ENABLE=true
      - RUSTFS_IDENTITY_OPENID_CONFIG_URL=${TRE_KEYCLOAK_URL}/realms/Dare-TRE
      - RUSTFS_IDENTITY_OPENID_CLIENT_ID=Dare-TRE-S3
      - RUSTFS_IDENTITY_OPENID_OTHER_AUDIENCES=Dare-TRE-UI,Dare-TRE-API
      - RUSTFS_IDENTITY_OPENID_CLIENT_SECRET=${MinioTreOpenidSecret}
      - RUSTFS_IDENTITY_OPENID_SCOPES=openid
      - RUSTFS_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC=off
      - RUSTFS_IDENTITY_OPENID_REDIRECT_URI=${MINIO_TRE_UI_URL}/rustfs/admin/v3/oidc/callback/default
      - RUSTFS_IDENTITY_OPENID_DISPLAY_NAME=Login with KeyCloak
      - RUSTFS_IDENTITY_OPENID_CLAIM_NAME=policy
    depends_on:
      rustfs_tre_perms:
        condition: service_completed_successfully
    volumes:
      - rustfs_TRE_data:/data/rustfs
    networks:
      - sub-net
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://127.0.0.1:9002/health && curl -f http://127.0.0.1:9003/rustfs/console/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    #  To resolve keycloak hostname for local development
    extra_hosts:
      - "keycloak.localtest.me=host-gateway"
