services:

  # ----- Data Egress - UI -----
  # -------------------------------------

  DataEgressUI:
    image: harbor.ukserp.ac.uk:443/dare-trefx/control-egress-ui:${dareVer}
    container_name: DataEgressUI
    restart: always
    networks:
      - sub-net
    ports:
      - 8100:8080
    depends_on:
      - DataEgressAPI
    environment:
      - DemoMode=${DemoMode}
      - KeyCloakDemoMode=${KeyCloakDemoMode}
      - Serilog__SeqServerUrl=http://seq:5341
      - DataEgressKeyCloakSettings__Authority=${EgressKeyCloakAuthority}
      - DataEgressKeyCloakSettings__MetadataAddress=${EgressKeyCloakMetadataAddress}
      - DataEgressKeyCloakSettings__BaseUrl=${EgressKeyCloakBaseRealmAddress}
      - DataEgressKeyCloakSettings__ClientId=${EgressKeyCloakClientID}
      - DataEgressKeyCloakSettings__ClientSecret=${EgressKeyCloakSecret}
      - DataEgressKeyCloakSettings__ValidAudiences=${EgressValidAudiences}
      - DataEgressKeyCloakSettings__Proxy=${useproxy}
      - DataEgressKeyCloakSettings__ProxyAddresURL=${proxyurl}
      - DataEgressKeyCloakSettings__BypassProxy=treAPI,seq-tre
      - DataEgressKeyCloakSettings__TokenExpiredAddress=${EgressKeyCloakTokenExpiredAddressUI}
      - DataEgressKeyCloakSettings__UseRedirectURL=${EgressKeyCloakUseRedirect}
      - DataEgressKeyCloakSettings__RedirectURL=${EgressKeyCloakClientUIRedirectURL}
      - DataEgressAPISettings__Address=http://DataEgressAPI:8080
      - MinioSettings__Url=http://localhost:9003
      - sslcookies=${sslcookies}
      - httpsRedirect=${httpsRedirect}

  # ----- Data Egress - API -----
  # -------------------------------------

  DataEgressAPI:
      image: harbor.ukserp.ac.uk:443/dare-trefx/control-egress-api:${dareVer}
      container_name: DataEgressAPI
      restart: always
      networks:
        - sub-net
      ports:
        - 8101:8080
      depends_on:
        postgresql:
          condition: service_healthy
        minioTRE:
          condition: service_healthy
      environment:
        - DemoMode=${DemoMode}
        - KeyCloakDemoMode=${KeyCloakDemoMode}
        - DemoModeDefaultP=password123
        - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=DATA-Egress;Include Error Detail=true;User Id=${PGLOGIN};Password=${PGPASSWORD};TrustServerCertificate=True;
        - RabbitMQ__HostAddress=rabbitmq-tre
        - Serilog__SeqServerUrl=http://seq:5341
        - TreKeyCloakSettings__Authority=${TreAPIKeyCloakAuthority}
        - TreKeyCloakSettings__MetadataAddress=${TreAPIKeyCloakMetadataAddress}
        - TreKeyCloakSettings__BaseUrl=${TreAPIKeyCloakBaseRealmAddress}
        - TreKeyCloakSettings__ClientId=${TreAPIKeyCloakClientId}
        - TreKeyCloakSettings__ClientSecret=${TreAPIKeyCloakSecret}
        - TreKeyCloakSettings__ValidAudiences=${TreAPIValidAudiences}
        - TreKeyCloakSettings__Proxy=${useproxy}
        - TreKeyCloakSettings__ProxyAddresURL=${proxyurl}
        - TreKeyCloakSettings__BypassProxy="treAPI,seq-tre"
        - TreKeyCloakSettings__TokenExpiredAddress=${TreAPIKeyCloakTokenExpiredAddressUI}
        - TreKeyCloakSettings__UseRedirectURL=${TreKeyCloakUseRedirect}
        - TreKeyCloakSettings__RedirectURL=${TreKeyCloakClientUIRedirectURL}
        - DataEgressKeyCloakSettings__Authority=${EgressKeyCloakAuthority}
        - DataEgressKeyCloakSettings__MetadataAddress=${EgressKeyCloakMetadataAddress}
        - DataEgressKeyCloakSettings__BaseUrl=${EgressKeyCloakBaseRealmAddress}
        - DataEgressKeyCloakSettings__ClientId=${EgressKeyCloakClientID}
        - DataEgressKeyCloakSettings__ClientSecret=${EgressKeyCloakSecret}
        - DataEgressKeyCloakSettings__ValidAudiences=${EgressKeyCloakClientID}
        - DataEgressKeyCloakSettings__Proxy=${useproxy}
        - DataEgressKeyCloakSettings__ProxyAddresURL=${proxyurl}
        - DataEgressKeyCloakSettings__BypassProxy="treAPI,seq-tre"
        - DataEgressKeyCloakSettings__TokenExpiredAddress=${EgressKeyCloakTokenExpiredAddressUI}
        - DataEgressKeyCloakSettings__UseRedirectURL=${EgressKeyCloakUseRedirect}
        - MinioSettings__Url=http://minioTRE:9000
        - MinioSettings__AccessKey=${TreMinioAdminUser}
        - MinioSettings__SecretKey=${TreMinioAdminPassword}
        - MinioSettings__BucketName=testbucket
        - MinioSettings__AdminConsole=http://minioIn:9001
        - TreAPISettings__Address=http://treapi:8080
        - DataEgressAPISettings__Address=http://DataEgressAPI:8100