name: DemoStack

# ----- Services -----

include:
  # ----- Application Services -----
  # - (Submission Layer, TRE Layer, Egress Layer)

  - ../ServiceStack/compose-manifests/applications/submission-layer.yml
  - ../ServiceStack/compose-manifests/applications/egress-layer.yml
  - ../ServiceStack/compose-manifests/applications/tre-layer.yml

  # ----- Shared Services -----
  # - Platform Service: (PostgreSQL, Adminer, Serilog, RabbitMQ)
  # - Auth Service: (Keycloak)
  # - Credentials Service: (Camunda, Vault, OpenLDAP, LDAP Init, phpLDAPadmin, Elastic Search)

  - ../ServiceStack/compose-manifests/shared/platform.yml
  - ../ServiceStack/compose-manifests/shared/auth.yml
  - ../ServiceStack/compose-manifests/shared/credentials.yml

  # - OMOP Lite Service: (OMOP Lite - Optional - Uncomment to enable)
  # - ../ServiceStack/compose-manifests/shared/omop-lite.yml

  # ----- Storage Services -----
  # (RustFS S3 - Submission & TRE)
  - ../ServiceStack/compose-manifests/storage/s3-tre.yml
  - ../ServiceStack/compose-manifests/storage/s3-submission.yml

# ----- Volumes -----

volumes:
  postgresql_data:
    driver: local
  postgresql_kc:
    driver: local
  s3_submission_data:
    driver: local
  s3_TRE_data:
    driver: local
  seq_data:
    driver: local
  rabbitdata:
    driver: local
  rabbitlogs:
    driver: local
  keycloak_data:
    driver: local
  data-protection:
    driver: local
  zeebe:
    driver: local
  elastic:
    driver: local
  kibana:
    driver: local
  vault_data:
    driver: local
  vault_logs:
    driver: local
  openldap_data:
    driver: local
  openldap_config:
    driver: local
  tre_process_models:
    driver: local

# ----- Shared Network & Configs -----

networks:
  sub-net:
    driver: bridge

