---

- name: 'download the {{ funnel_version }} funnel binary archive'
  ansible.builtin.get_url:
    url: "https://github.com/ohsu-comp-bio/funnel/releases/download/{{ funnel_version }}/funnel-linux-amd64-{{ funnel_version }}.tar.gz"
    dest: '/tmp/funnel.tar.gz'
    mode: 0644

- name: 'extract the funnel binary'
  ansible.builtin.unarchive:
    src: '/tmp/funnel.tar.gz'
    dest: '/usr/local/bin'

- name: 'ensure funnel user exists'
  ansible.builtin.user:
    name: 'funnel'
    system: true
    shell: '/usr/sbin/nologin'
    create_home: false

- name: 'create funnel config directory'
  ansible.builtin.file:
    path: '/etc/funnel/'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: 0755

- name: 'create funnel working directory'
  ansible.builtin.file:
    path: '/var/lib/funnel/'
    state: 'directory'
    owner: 'funnel'
    group: 'funnel'
    mode: 0755

- name: 'create funnel log directory'
  ansible.builtin.file:
    path: '/var/log/funnel/'
    state: 'directory'
    owner: 'funnel'
    group: 'funnel'
    mode: 0755

- name: 'create the funnel config'
  ansible.builtin.template:
    src: 'funnelconfig.yml.j2'
    dest: '/etc/funnel/funnelconfig.yml'
    owner: 'root'
    group: 'root'
    mode: 0644

- name: 'create funnel systemd unit file'
  ansible.builtin.copy:
    src: 'funnel.service'
    dest: '/etc/systemd/system/funnel.service'
    owner: 'root'
    group: 'root'
    mode: 0644

- name: 'reload systemd to pull in the new file'
  ansible.builtin.systemd:
    daemon_reload: true

- name: 'enable start and enable funnel'
  ansible.builtin.systemd:
    name: 'funnel'
    state: 'started'
    enabled: true
