services:

  # ------ PostgreSQL Database ------
  # ------------------------------------------

  postgresql:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${PGLOGIN}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=DARE-Control
    networks:
      - sub-net
    ports:
      - "5432:5432"
    volumes:

    # ----- $CONFIG_PATH Configuration -----

    # Use CONFIG_PATH when using the image in the compose stack.
    # - Update the CONFIG_PATH variable in the .env file to point to the directory.

      - "postgresql_data:/var/lib/postgresql/data"
      - ${CONFIG_PATH}/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U ${PGLOGIN} -d keycloak"]

  # ----- Adminer Database Management ------
  # ---------------------------------------------

  adminer:
    image: adminer
    restart: always
    networks:
      - sub-net
    ports:
      - 8087:8080
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=psql
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=postgres
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "adminer", "8080"]
      timeout: 45s
      interval: 10s
      retries: 10


  # ----- Seq Log Server ------
  # ----------------------------------
  seq:
    image: datalust/seq:2025.1.14095
    container_name: seq
    restart: always
    networks:
      - sub-net
    ports:
      - 5341:80
    volumes:
      - seq_data:/data
    environment:
      - ACCEPT_EULA=Y

# ----- RabbitMQ Message Broker ------
# -------------------------------------------
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitdata:/var/lib/rabbitmq/
      - rabbitlogs:/var/log/rabbitmq
    networks:
      - sub-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3