apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: submission-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: dare-control-submission
  destination:
    namespace: dare-control-submission
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:  
    - CreateNamespace=true 
    - ServerSideApply=true
    retry:
      limit: 5
      backoff: 
        duration: "30s"
        factor: 2
        maxDuration: "10m0s"
  source:
    repoURL: "harbor.ukserp.ac.uk/dare-trefx/chart"
    chart: submission-stack
    targetRevision: "1.0.0"
    helm:
      valuesObject: 
        config:
          fullnameOverride: "dare-control-submission"

        global:
          # this makes the chart autogenerate all secrets
          dev: true
          argoProject: dare-control-submission
          namespace: dare-control-submission
          oidc:
            authority: "http://keycloak.localtest.me/realms/Dare-Control"
          ingress:
            enabled: false
          storage:
            defaultClass: "standard"
            rwxClass: "standard"

        submission:
          chartVersion: "1.0.0"

          api:
            image:
              repository: harbor.ukserp.ac.uk/dare-trefx/control-main-api
              tag: "2.12.0"

          ui:
            image:
              repository: harbor.ukserp.ac.uk/dare-trefx/control-main-ui
              tag: "2.12.0"

          minioBucketName: "testbucket"

          queryImage:
            sql: "ukserp/runsql:1.0.0"
            graphql: "harbor.ukserp.ac.uk/dare-trefx/control-tre-hasura:2.12.0"

        keycloak:
          enabled: true

        minio:
          enabled: true
          repoURL: 'https://operator.min.io/'
          chart: tenant
          chartVersion: "7.1.1"

          ecParity: "EC:1"
          ecStripeSize: "2"

          tenantName: "submission-layer"
          firstPool:
            servers: 1
            volumesPerServer: 2
            size: 10Gi
            storageClassName: standard
            storageTierNodeLabel: "2"

        operators:
          minio:
            enabled: true

          postgres:
            enabled: true

          rabbitmq:
            enabled: true

        rabbitmq-cluster-operator:
          clusterOperator:
            watchAllNamespaces: true
            image:
              repository: bitnamilegacy/rabbitmq-cluster-operator

          msgTopologyOperator:
            enabled: true
            watchAllNamespaces: true
            image:
              repository: bitnamilegacy/rmq-messaging-topology-operator

          rabbitmqImage:
            repository: bitnamilegacy/rabbitmq

          credentialUpdaterImage:
            repository: bitnamilegacy/rmq-default-credential-updater