# Patch the coredns ConfigMap in kube-system
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        rewrite name exact keycloak.localtest.me keycloak.dare-control-submission.svc.cluster.local
        rewrite name exact minio.localtest.me submission-layer-console.dare-control-submission.svc.cluster.local
        rewrite name exact minio-api.localtest.me minio.dare-control-submission.svc.cluster.local

        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30 {
           disable success cluster.local
           disable denial cluster.local
        }
        loop
        reload
        loadbalance
    }
